### PR TITLE
Follow

### PR DESCRIPTION
**Pull request by Heyjp**

### CODE REVIEW

**Comment by shibatas** [comment]
@Heyjp Looks like `ProjectCard.js` didn't get merged with `dev` correctly. `ProjectCard` class is defined twice in there. Could you take a look? Thanks!

**Review by shohei-shibata — APPROVED** [review]
Hey thanks for fixing the weird arrow function issue. Now everything is working for me and it looks good! 

I also like the dashboard page idea. Maybe we could also list "my projects" there too?

**Review by AlexGherardelli — CHANGES_REQUESTED** [review]
I checked out this PR last week and everything worked okay. Now though I'm having two problems:
1) It does not compile because  "Module not found: Error: Can't resolve 'react-icons/lib/fa/star'"
2) It has some merge conflicts with dev

Could you solve these two issues? I'm happy to approve it and merge it afterwards

**Comment by Heyjp** [comment]
Can you let me know if the `react-icons` folder still exists in your `package.json` otherwise i'll have to include and push it again. Otherwise I think I've fixed most of the conflicts.

**Review by AlexGherardelli — APPROVED** [review]

**Pull request merged**
