### PR TITLE
Feature/redux

### PR DESCRIPTION
**Pull request by Heyjp**

### CODE REVIEW

**Comment by Heyjp** [comment]
Just implemented the skeleton for redux and changed out a couple of the props within the routes.

**Comment by shibatas** [comment]
Just want to check... if we all agree to implement Redux, we would connect all the child components to the Redux store so that we don't have to pass down `user` and `projects` as props anymore, correct? Just want to make sure, because right now they're being passed down anyway, and looks like there's no benefit! (Basically I'm for implementing Redux... good chance to learn it for me :) )

**Comment by Heyjp** [comment]
Ah yeah. So I wanted to get a redux skeleton in that wouldn't break or make any major changes that would allow everyone to carry on with what they were doing. 

Ideally routes would look something like

```
const routes= () => {
  return (
    <Router>
      <div>
        <Nav>
          <Switch>
            <Route path="/" component={Main} />
            <Route path="/about" component={About} />
            <Route path="/contact" component={Contact} />
          </Switch>
        </Footer> 
      </div>
    </Router>
  )
}
```

So I completely agree with moving all the props to the child components. In my mind this way although slightly longer will allow everyone to pick say 1 component and refactor it to connect to the store and move all methods to the component or have them passed down from the store. Hope that makes sense.

**Comment by shibatas** [comment]
Thanks for the clarification. Makes sense. I think everyone taking pieces and refactoring will be a great way to learn. Anyway let's see what @AlexGherardelli thinks!

**Comment by AlexGherardelli** [comment]
Hey - I'm pulling this branch now to have a look at the code and test it. Right now it has one merge conflict - I still have to get comfortable with Redux, so it's probably NOT a good idea if I resolve it myself :P @Heyjp 

If everything is okay, I'll merge it later!

**Review by AlexGherardelli — APPROVED** [review]

**Pull request merged**
