### PR TITLE
Bug/dropdown

### PR DESCRIPTION
**Pull request by Heyjp**
Created a dropdown for the categories section on create projects.  What do you think about the style / colors? 

Should I add a method to add new categories?

### CODE REVIEW

**Review by AlexGherardelli — CHANGES_REQUESTED** [review]
Looks nice! 👍 Couple of little improvements (but I'm happy to merge this without them: first, close the dropdown when not in focus; second, do not call it tag (in the drop down), which could be confusing since it's called Categories just right above it!

There are also a couple of minor conflicts, as soon as they are resolved I'm ready to merge it!

**Comment by shibatas** [comment]
Hey I like it too! I did notice that the reset button doesn't work when some categories are selected. Also, maybe this can be addressed later but what's your thought on how to handle the interface to create a new category? (right now there is no text field to handle it)

**Comment by Heyjp** [comment]
Encountering some issues here, like when I was merging, it's just gone ahead and deleted some of the files from the other branches. I need to do some research on how to undelete those. Sorry might take some time.

**Comment by Heyjp** [comment]
Ok I think I have fixed the missing file issue. Had to `checkout` all the files from development just to make sure, so the file changes may be a bit crazy now. 

But all the issues I believe have been fixed that you requested, if both of you can take a look and let me know. Would appreciate it.

**Comment by shibatas** [comment]
Just checked it out. I confirm that reset and unfocus works! Found one more little issue though :(  When in "edit project", if I click on the categories dropdown the form gets submitted... this doesn't happen when creating a new project. Other than that I'm good with it!

**Review by AlexGherardelli — APPROVED** [review]

**Pull request merged**
