### PR TITLE
User status

### PR DESCRIPTION
**Pull request by shohei-shibata**
* User-project relationships like "owner" and "following" is consolidated into a child schema within the `Project` model in the database.
* Created `projectStatus.js` file which contain functions to make accessing above status information easier.
* Frontend code was modified to use the new data format.

### CODE REVIEW

**Review by Heyjp — CHANGES_REQUESTED** [review]
Just tested out your changes. Currently it won't let me create a project when I'm logged in. I type in all the information and submit it and my DB isn't updated with a new project.

I like the changes you made with the `ProjectUsersSchema`. It'l make both users and owners easier to track and even people can potentially hand over ownership to someone else. 👍 

Also the changes to the follow icon to atoms is nice. But I'm getting the issue again with being the owner and being able to follow my own projects. Since they are fairly small components maybe they could also be consolidated into one. But this is pretty minor.

Just had a brief look but since I encountered the project issue I didn't look much deeper. Let me know if it's just something on my end.

**Review by AlexGherardelli — CHANGES_REQUESTED** [review]
I am also having the same problem Jamie is having: when logged in, I cannot create new projects. Except this, everything looks nice! 👍

**Comment by shibatas** [comment]
@AlexGherardelli @Heyjp 
The issue with posting new project should be fixed now, as well as hiding the follow button for owned projects. Please check it again. Thanks!

**Comment by AlexGherardelli** [comment]
I checked very, very quickly, but it still not working for me :(

**Comment by Heyjp** [comment]
Existing projects are still giving me the option to follow if i'm owner, but new ones do not so I think it will be a case of just updating my local projects. So 👍 from me.

**Review by Heyjp — APPROVED** [review]

**Review by AlexGherardelli — APPROVED** [review]

**Comment by AlexGherardelli** [comment]
Hi @shibatas. There are a few conflicts with dev - I started resolving them, but then I was not sure in some points which parts of code should be kept. If you could resolve them, then this can be merged asap. Thanks!

**Comment by shibatas** [comment]
Cancelling this PR to work out the issues within `dev` first. Will make another PR later for this branch.

**Pull request closed without merging**
